name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: rdecatri/metrics@master
        with:
          base: header
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKA_TOKEN }}
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_wakatime_languages_other: yes



          # plugin_isocalendar: yes
          # plugin_languages: yes
          # plugin_stars: yes
          # config_order: base.header, isocalendar, languages, stars

